const additives = [
    {
        brand: 'Tropica',
        models: ['Plant Growth Specialised ', 'Plant Growth Premium', 'Nutrition Capsules'],
    },
    {
        brand: 'Ultum Nature Systems',
        models: ['Plant Food – Iron', 'Plant Food – All in One'],
    },
    {
        brand: 'DOOA',
        models: ['Wabi-kusa Mist', 'Suikei Liquid'],
    },
    {
        brand: 'Aqua Design Amano',
        models: [
            'Brighty K',
            'Green Brighty Neutral K',
            'Green Brighty Nitrogen',
            'Green Brighty Mineral',
            'Green Brighty Iron',
            'Green Brighty Step 1',
            'Green Brighty Step 2',
            'Green Brighty Step 3',
            'Green Brighty Special Lights',
            'Green Brighty Special Lights Shade',
        ],
    },
    {
        brand: 'Seachem',
        models: [
            'Acid Regulator',
            'Alkaline Regulator',
            'American Cichlid Salt',
            'Arowana Buffer',
            'Betta Basics',
            'Brackish Salt',
            'Cichlid Lake Salt',
            'Cichlid Trace',
            'Discus Buffer',
            'Discus Trace',
            'Fresh Trace',
            'Gold Basics',
            'Gold Buffer',
            'Gold Salt',
            'Gold Trace',
            'Malawi / Victoria Buffer',
            'Neutral Regulator',
            'Liquid Neutral Regulator',
            'Tanganyika',
            'Acid Buffer',
            'Alkaline Buffer',
            'Equilibrium',
            'Flourish',
            'Flourish Advance',
            'Flourish Excel',
            'Flourish Iron',
            'Flourish Nitrogen',
            'Flourish Phosphorus',
            'Flourish Potassium',
            'Flourish Tabs',
            'Flourish Trace',
            'Plant Pack Fundamentals',
            'Plant Pack Enhancer NPK',
        ],
    },
]

export default additives
