export default [
    {
        brand: 'Chihiros',
        models: [
            'ES-1200',
            'ES-1200EX',
            'ES-1200EX2',
            'ES-150',
            'ES-300',
            'ES-600',
            'ES-600EX',
            'ES-600EX2',
        ],
    },
    {
        brand: 'Aqua Design Amano',
        models: [
            'ES-1200',
            'ES-1200EX',
            'es-1200ex2',
            'ES-150',
            'ES-2400',
            'ES-2400EX',
            'ES-2400EX2',
            'ES-300',
            'ES-600',
            'ES-600EX',
            'ES-600EX',
        ],
    },
    {
        brand: 'Aqueon',
        models: [
            'QuietFlow 125',
            'QuietFlow 55',
            'QuietFlow 75',
            'QuietFlow AT10',
            'QuietFlow AT15',
            'QuietFlow AT30',
            'QuietFlow AT40',
            'QuietFlow E Extra Small 3',
            'QuietFlow E Large 40',
            'QuietFlow E Medium 20',
            'QuietFlow E Small 10',
            'QuietFlow LED Pro 10',
            'QuietFlow LED Pro 20',
            'QuietFlow LED Pro 30',
            'QuietFlow LED Pro 50',
            'QuietFlow LED Pro 75',
        ],
    },
    {
        brand: 'Azoo',
        models: [
            'External Power Filter',
            'Mignon MF - 1000',
            'Mignon MF - 150',
            'Mignon MF - 240',
            'Mignon MF - 360',
            'Mignon MF - 60',
            'Mignon MF - 800',
            'Oxygen Plus Bio - Filter No. 1',
            'Oxygen Plus Bio - Filter No. 10',
            'Oxygen Plus Bio - Filter No. 11',
            'Oxygen Plus Bio - Filter No. 12',
            'Oxygen Plus Bio - Filter No. 2',
            'Oxygen Plus Bio - Filter No. 3',
            'Oxygen Plus Bio - Filter No. 4',
            'Oxygen Plus Bio - Filter No. 5',
            'Oxygen Plus Bio - Filter No. 6',
            'Oxygen Plus Bio - Filter No. 7',
            'Oxygen Plus Bio - Filter No. 8',
            'Oxygen Plus Bio - Filter No. 9',
            'Power Head 1200',
            'Power Head 180',
            'Power Head 1800',
            'Power Head 2500',
            'Power Head 3200',
            'Power Head 60',
            'Power Head 600',
            'Skim 250',
            'Submersible Filter 1200',
            'Submersible Filter 180',
            'Submersible Filter 1800',
            'Submersible Filter 2500 ',
            'Submersible Filter 60',
            'Submersible Filter 600',
        ],
    },
    {
        brand: 'Eheim',
        models: [
            'Aquacompact 60',
            'Classic 150',
            'Classic 1500XL',
            'Classic 250',
            'Classic 350',
            'Classic 600',
            'Experience 150',
            'Experience 250',
            'Experience 250T',
            'Experience 350',
            'Professionel 3 1200XL',
            'Professionel 3 1200XLT',
            'Professionel 3e 450',
            'Professionel 3e 600T',
            'Professionel 3e 700',
            'Professionel 4e 240',
            'Professionel 4e 250T',
            'Professionel 4e 350',
            'Professionel 4e 350T',
            'Professionel 4e 600',
        ],
    },
    {
        brand: 'Fluval',
        models: [
            '106',
            '206',
            '306',
            '406',
            'C2',
            'C3',
            'C4',
            'FX4',
            'FX6',
            'G3',
            'G6',
            'Nano',
            'U1',
            'U2',
            'U3',
            'U4',
        ],
    },
    {
        brand: 'Hydor',
        models: [
            'Internal',
            'Mini Internal',
            'Prime 10',
            'Prime 20',
            'Prime 30',
            'Professional 150',
            'Professional 250',
            'Professional 350',
            'Professional 450',
            'Professional 600',
            'Slim-Skim Nano 135.35',
            'Slim-Skim Nano 250.65',
        ],
    },
    {
        brand: 'Marineland',
        models: [
            'Emperor',
            'Magniflow 160',
            'Magniflow 220',
            'Magniflow 360',
            'Magnum Polishing',
            'Penguin ',
            'Penguin 100',
            'Penguin 150',
            'Penguin 200',
            'Penguin 350',
            'Penguin 75',
        ],
    },
    {
        brand: 'Shiruba',
        models: [
            'PF-1000',
            'PF-120',
            'PF-240',
            'PF-360',
            'PF-60',
            'PF-800',
            'PH-201',
            'PH-203',
            'XB-2040',
            'XB-2060',
            'XB-2100',
            'XB-301',
            'XB-303',
            'XB-305',
            'XB-308',
            'XB-310',
            'XB-3101',
            'XB-312',
        ],
    },
    {
        brand: 'SunSun',
        models: [
            'HQJ-500S',
            'HQJ-700l',
            'HQJ-700S',
            'HQJ-900I',
            'HW-302',
            'HW-303A',
            'HW-303B',
            'HW-304A',
            'HW-304B',
            'HW-402A',
            'HW-402B O',
            'HW-403A',
            'HW-403B OU',
            'HW-404A OU',
            'HW-404B',
            'HW-504A',
            'HW-504B',
            'HW-505A',
            'HW-505B',
            'HW-602',
            'HW-603',
            'JP-022F',
            'JP-023F',
            'JP-024F',
            'JP-025F',
            'JP-032F',
            'JP-033F',
            'JP-042F',
            'JP-043F',
            'JP-044F',
            'JP-082',
            'JP-083',
            'JP-084',
            'JP-085',
            'JP-092',
            'JP-093',
            'JP-094',
        ],
    },
    {
        brand: 'Tetra',
        models: [
            'Whipser EX 20',
            'Whisper 10i',
            'Whisper 20i',
            'Whisper 3i',
            'Whisper 40i',
            'Whisper EX 30',
            'Whisper EX 45',
            'Whisper EX 70',
            'Whisper PF 10',
            'Whisper PF 20',
            'Whisper PF 30',
            'Whisper PF 40',
            'Whisper PF 60',
        ],
    },
]
