const fish = [
    'Sixray corydoras',
    "Britski's catfish",
    'Emerald catfish',
    'Hognosed brochis',
    'Cascarudo',
    "Adolfo's catfish",
    'Banded corydoras',
    'Masked corydoras',
    'Barred-tail corydoras',
    'Blackstripe corydoras',
    'Blacktop corydoras',
    'Blue corydoras',
    'Bluespotted corydoras',
    'Bronze corydoras',
    'Caracha',
    "Ehrhardt's corydoras",
    "Evelyn's cory",
    'Loxozonus cory',
    'Corydoras Catfish',
    'Long nosed arched cory',
    'Dwarf corydoras',
    'Elegant corydoras',
    'False network catfish',
    'False spotted catfish',
    'Green gold catfish',
    'Guapore corydoras',
    'Mosaic corydoras',
    'Panda corydoras',
    'Pastaza corydoras',
    'Peppered corydoras',
    'Pink corydoras',
    'Pygmy corydoras',
    'Sailfin corydoras',
    'Salt and pepper catfish',
    "Schwartz's catfish",
    'Spotted corydoras',
    "Sterba's corydoras",
    "Sychr's catfish",
    'Tailspot corydoras',
    'Threestripe corydoras',
    'Xingu corydoras',
    'Julii corydoras',
    'Flagtail catfish',
    'Bristlenose pleco',
    'Gold nugget pleco',
    'Whiptail catfish',
    'Twig catfish',
    'Panaque',
    'Pineapple pleco',
    'Hypostomus plecostomus',
    'Ancistrus ',
    'Leopard sailfin pleco',
    'Zebra pleco',
    'Sailfin catfish',
    'Otocinclus affinis',
    'Black phantom tetra',
    'Black neon tetra',
    'Bleeding heart tetra',
    'Bloodfin tetra',
    'Blue tetra',
    'Bucktooth tetra',
    'Buenos Aires tetra',
    'Cardinal tetra',
    'Cave tetra',
    'Diamond tetra',
    'Ember tetra',
    'Emperor tetra',
    'Flame tetra',
    'Garnet tetra',
    'Glass bloodfin tetra',
    'Glowlight tetra',
    'Golden pristella tetra',
    'Green neon tetra',
    'Head and tail light tetra',
    'January tetra',
    'Lemon tetra',
    'Neon tetra',
    'Ornate tetra',
    'Penguin tetra',
    'Red Eye tetra',
    'Red phantom tetra',
    'Rosy tetra',
    'Royal tetra',
    'Rummy-nose tetra',
    'Splash tetra',
    'Serpae tetra',
    'Silvertip tetra',
    'X-ray tetra',
    'Congo tetra',
    'Jellybean tetra',
    'Long-fin tetra',
    'Niger tetra',
    'Yellow-tailed Congo tetra',
    'Golden pencilfish',
    'Hockeystick pencilfish',
    'Barred pencilfish',
    'Dwarf pencilfish',
    'Coral-red pencilfish',
    'Three-lined pencilfish',
    'One-lined Pencilfish',
    'Sunshine peacock cichlid',
    'Pale usisya aulonocara',
    'Red fin hap',
    'Eureka red peacock',
    'Blue dolphin cichlid',
    'Afra cichlid',
    'Rusty cichlid',
    "Fuelleborn's cichlid",
    'Electric yellow cichlid',
    'Electric blue cichlid',
    'Malawi eyebiter',
    'Hongi',
    'Yellow Top Mbamba',
    'Auratus cichlid',
    'Chipokee cichlid',
    'Blue johanni cichlid',
    'Pearl of Likoma',
    'Red zebra cichlid',
    'Cobalt blue cichlid',
    'Kenyi cichlid',
    'Fusco',
    "Livingston's cichlid",
    'Kaligono',
    'Venustus cichlid',
    'Red empress cichlid',
    'Bumblebee cichlid',
    'Yellow-tail acei',
    'Johanni cichlid',
    'Dwarf Mbuna',
    'Saulosi',
    'Malawi barracuda',
    "Agassiz's dwarf cichlid",
    'Cockatoo dwarf cichlid',
    'Panda dwarf cichlid',
    'Blue ram',
    'Bolivian ram',
    'Angelfish',
    'Altum angelfish\t',
    'Spotted angelfish',
    'Discus fish',
    'Chocolate cichlid',
    'Oscar',
    'Blood parrot cichlid',
    'Flowerhorn cichlid',
    'Cherry barb',
    'Clown barb',
    'Gold barb',
    'Panda barb',
    'Snakeskin barb',
    'Bala shark',
    'Siamese algae eater',
    'Flying fox',
    'Red-tailed black shark',
    'Rainbow shark',
    'Harlequin rasbora',
    'Clown rasbora',
    'Dwarf rasbora',
    'Pearl danio',
    'Giant danio',
    'Zebra danio',
    'Goldfish',
    'Koi',
    'Clown loach',
    'Horseface loach',
    'Kuhli loach',
    'Dwarf botia',
    'Guppy',
    'Guppy endler',
    'Common molly',
    'Black molly',
    'White molly',
    'Golden molly',
    'Balloon molly',
    'Sailfin molly',
    'Lyretail molly',
    'Dalmatian molly',
    'Common platy',
    'Southern platy',
    'Variable platy\t',
    'Common swordtail',
    'Dwarf gourami',
    'Pearl gourami',
    'Betta Siamese fighting fish',
    'Scarlet betta',
    "Boeseman's rainbowfish",
    "Duboulayi's rainbowfish",
    'Neon rainbowfish',
    'Dwarf pufferfish',
    'Giant freshwater pufferfish',
    'Amazon puffer',
    'Black devil stingray',
    'Black ghost knifefish',
    'Killifish ',
]

export default fish
