export default [
    'Aciotis Acuminifolia',
    'Acmella Repens',
    'Acorus Gramineus',
    'Acorus Pusillus',
    'Aegapropila Linnaei',
    'Aeschynomeme Fluitans',
    'African Water Fern / Bolbitis Heudelotii',
    'Aldrovanda Vesiculosa',
    'Alternanthera Aquatica',
    'Alternanthera Bettzickiana',
    'Alternanthera Bettzickiana Red',
    'Alternanthera Lilacana',
    'Alternanthera Reineckii',
    'Alternanthera Reineckii "Mini"',
    'Alternanthera Reineckii "Rosaefolia"',
    'Alternanthera Reineckii Bronze',
    'Ammania Gracilis',
    'Ammania Praetermisa',
    'Ammania Senegalensis',
    'Anubias Barteri',
    'Anubias Barteri "Coffeefolia"',
    'Anubias Barteri Broad Leaf',
    'Anubias Barteri Butterfly',
    'Anubias Barteri Nana Long Wavy',
    'Anubias Barteri Round "Golden Coin"',
    'Anubias Barteri Striped',
    'Anubias Barteri Var "Nana"',
    'Anubias Congensis',
    'Anubias Congensis Broad',
    'Anubias Congensis Mini',
    'Anubias Frazeri',
    'Anubias Hastifolia',
    'Anubias Heterophylla',
    'Anubias Lanceolata',
    'Anubias Minima',
    'Anubias Nana',
    'Anubias Nana "Wrinkle Leaf"',
    'Anubias Nana Golden',
    'Anubias Nana Pangolino',
    'Anubias Nana Petitie',
    'Anubias Nana Pinto',
    'Anubias Nana Thick Leaf',
    'Anubias Nangi',
    'Anubias Short and Sharp',
    'Apongogeton Madagascarniensis',
    'Aponogeton Boivinianus',
    'Aponogeton Capuronii',
    'Aponogeton Longipumuosus',
    'Aponogeton Natans',
    'Aponogeton Ulvaceus',
    'Aridarum Caulecens Sabertooth',
    'Aridarum Mini',
    'Aridarum Narrow',
    'Aurora',
    'Azolla Filiculoides',
    'Bacon Australis',
    'Bacopa Amlexicaulis',
    'Bacopa Carliniana Red',
    'Bacopa Caroliana',
    'Bacopa Monnieri',
    'Barclaya Longifolia',
    'Blepharostoma Trichophyllum "Mini Pearl Moss"',
    'Bolbitis Heteroclita',
    'Bolbitis Heudelott Difformis',
    'Bucephalandra Arrogant Blue',
    'Bucephalandra Athena',
    'Bucephalandra Belindae',
    'Bucephalandra Belindae Mini',
    'Bucephalandra Black Angel',
    'Bucephalandra Black Centipede',
    'Bucephalandra Black Marble',
    'Bucephalandra Black Pearl',
    'Bucephalandra Black Tears',
    'Bucephalandra Black Venti',
    'Bucephalandra Blue Sea',
    'Bucephalandra Broad Wavy',
    'Bucephalandra Brownie Blue',
    'Bucephalandra Brownie Brown',
    'Bucephalandra Brownie Firebird',
    'Bucephalandra Brownie Ghost',
    'Bucephalandra Brownie Helena',
    'Bucephalandra Brownie Hermes',
    'Bucephalandra Brownie Jade',
    'Bucephalandra Brownie Jae',
    'Bucephalandra Brownie Metallica',
    'Bucephalandra Brownie Phantom',
    'Bucephalandra Brownie Pheonix',
    'Bucephalandra Brownie Purple',
    'Bucephalandra Brownie Red',
    'Bucephalandra Brownie Selena',
    'Bucephalandra Brownie Sugar',
    'Bucephalandra Cascade King',
    'Bucephalandra Catherinae Green',
    'Bucephalandra Catherinae Green Purple',
    'Bucephalandra Catherinae Mini',
    'Bucephalandra Catherinae Red',
    'Bucephalandra Catherinae Red Mini',
    'Bucephalandra Centipede Red Blood',
    'Bucephalandra Dark Skeleton King',
    'Bucephalandra Dark Wave',
    'Bucephalandra Deep Purple',
    'Bucephalandra Fino Mimosa Bilblis Blue Sky',
    'Bucephalandra Fino Sherry',
    'Bucephalandra Flora',
    'Bucephalandra Goliath',
    'Bucephalandra Green Godzilla',
    'Bucephalandra Green Skeleton King',
    'Bucephalandra Green Tears',
    'Bucephalandra Green Wavy',
    'Bucephalandra Hades',
    'Bucephalandra Isabella',
    'Bucephalandra Kapit Sultan Red',
    'Bucephalandra Kecil Dark Green',
    'Bucephalandra Kedagane Round',
    'Bucephalandra Kedagang Long',
    'Bucephalandra Kedagang Mini',
    'Bucephalandra Kedagang Original',
    'Bucephalandra Kedagang Purple',
    'Bucephalandra Kir Royale',
    'Bucephalandra Krivbass',
    'Bucephalandra Laina Green',
    'Bucephalandra Lemandau Mini Purple',
    'Bucephalandra Little Dagger',
    'Bucephalandra Little Red Star',
    'Bucephalandra Maestro Blue',
    'Bucephalandra Magnum Blue',
    'Bucephalandra Malinau Apple Leaf',
    'Bucephalandra Medusa',
    'Bucephalandra Melawi Black',
    'Bucephalandra Melawi Blue',
    'Bucephalandra Melawi Green',
    'Bucephalandra Micrantha',
    'Bucephalandra Midnight Blue',
    'Bucephalandra Mini Coin',
    'Bucephalandra Motelyana Black Purple',
    'Bucephalandra Mukok Red',
    'Bucephalandra Odyssey',
    'Bucephalandra Peacock',
    'Bucephalandra Pink Bilblis',
    'Bucephalandra Pink Lage',
    'Bucephalandra Purple Blue',
    'Bucephalandra Pygmae',
    'Bucephalandra Rainbow Frost',
    'Bucephalandra Raven',
    'Bucephalandra Red',
    'Bucephalandra Red Aphrodisiac',
    'Bucephalandra Red Blade',
    'Bucephalandra Red Cerberus',
    'Bucephalandra Red Cherry',
    'Bucephalandra Red Cloud',
    'Bucephalandra Red Shot',
    'Bucephalandra Royal',
    'Bucephalandra Sherry',
    'Bucephalandra Silver Skine',
    'Bucephalandra Super Mini Catherinae',
    'Bucephalandra Super Red',
    'Bucephalandra Sweet Mambo',
    'Bucephalandra Theia Black',
    'Bucephalandra Thick Brown',
    'Bucephalandra Ultra Green',
    'Bucephalandra Velvet',
    'Bylxa Japonica',
    'Cabomba Aquatica',
    'Cabomba Piauhyensis Red',
    'Cardamin Lyrata Vietnam',
    'Cardamine Lytrata',
    'Christmas Moss',
    'Creeping Moss',
    'Crepidomanes Auriculatum / Asplenium CF. Normale',
    'Crinum Calamistratum',
    'Crinum Thaianum',
    'Cryptocoryne "Tropica"',
    'Cryptocoryne Balansae',
    'Cryptocoryne Becketii',
    'Cryptocoryne Beckett "Petchii"',
    'Cryptocoryne Blassii',
    'Cryptocoryne Cordata',
    'Cryptocoryne Costata',
    'Cryptocoryne Crispatula',
    'Cryptocoryne Crispatula Tonkinensis',
    'Cryptocoryne Flamingo',
    'Cryptocoryne Fusca',
    'Cryptocoryne Hendriki',
    'Cryptocoryne Hudoroi',
    'Cryptocoryne Lucens',
    'Cryptocoryne Lutea',
    'Cryptocoryne Mioya',
    'Cryptocoryne Nurii',
    'Cryptocoryne Parva',
    'Cryptocoryne Pontederiifolia',
    'Cryptocoryne Retrospiralis',
    'Cryptocoryne Sahalii',
    'Cryptocoryne Silver Queen',
    'Cryptocoryne Spiralis',
    'Cryptocoryne Sri Lanka',
    'Cryptocoryne Striolata',
    'Cryptocoryne Undulatas',
    'Cryptocoryne Usteriana',
    'Cryptocoryne Walkeri',
    'Cryptocoryne Wendtii "Brown"',
    'Cryptocoryne Wendtii "Kompackt"',
    'Cryptocoryne Wendtii Green',
    'Cryptocoryne Wendtii Green Gecko',
    'Cryptocoryne Willisii',
    'Cryptocoryne X Purpurea',
    'Cryptocoryne Yujii',
    'Crytocoryne Cordata Rosanervig',
    'Cyperus Helferi',
    'Cyrptocoryne Undulatus "Red"',
    'Dwarf Hair grass',
    'Dwarf Nomaphila Siamensis',
    'Echinodorus Aflame',
    'Echinodorus Big Bear',
    'Echinodorus Bleherie / Amazon Sword',
    'Echinodorus Fancy Twist',
    'Echinodorus Grandifolius',
    'Echinodorus Hadi Red Pearl',
    'Echinodorus Horzontalis Mini',
    'Echinodorus Major / Martii',
    'Echinodorus Marble Queen',
    'Echinodorus Montevidensis',
    'Echinodorus Muricatus',
    'Echinodorus Opacus',
    'Echinodorus Ozelot',
    'Echinodorus Ozelot Green',
    'Echinodorus Parviflorus',
    'Echinodorus Peruensis',
    'Echinodorus Red Rubin',
    'Echinodorus Red Rubin "Narrow"',
    'Echinodorus Rose',
    'Echinodorus Small Bear',
    'Echinodorus Stellata / Pogostemon Stellata',
    'Echinodorus Tenellus',
    'Echinodorus Xinguensis',
    'Elatine Hydropiper',
    'Eleocharis Vivipara',
    'Fissidens Fontanus',
    'Fissidens Nobilis',
    'Flame Moss',
    'Giant Java Fern',
    'Glossostigma Elatinoides',
    'Gratiola Red',
    'Hemiantuhs Callitrichoides',
    'Hemigraphs Repanda',
    'Homalomena Humilis',
    'Homalomena Insignis',
    'Homalomena Silver',
    'Homalomena SP Sekadau South',
    'Homalomena Sungai Panjang',
    'Hydrocotyle Leucocephala',
    'Hydrocotyle Sibthorpioides',
    'Hydrocotyle Tripartita',
    'Hydrocotyle Verticillata',
    'Hygrophila Difformis',
    'Hygrophila Pinnatifida',
    'Hygrophilla Lancea "Araguaia"',
    'Java Fern',
    'Java Fern "Lettuce"',
    'Java Fern "Thors Hammer"',
    'Java Fern "Windelov"',
    'Java Moss',
    'Lagenandra Meeboldii "Red"',
    'Limnophila Aromatica',
    'Limnophila Heterophylla',
    'Lobelia Cardinalis',
    'Ludwigia Arcuata',
    'Ludwigia Inclinata',
    'Ludwigia Natas Super Red',
    'Ludwigia Ovalis',
    'Ludwigia Palustris',
    'Ludwigia Peruensis / Gladulosa Var Diamond',
    'Ludwigia Repens',
    'Ludwigia Sedioides',
    'Ludwigia Sp. Pink',
    'Marimo Moss Ball',
    'Marsilea Crenata',
    'Mayaca Fluviatilis',
    'Micranthemum "Monte Carlo"',
    'Micranthemum Micranthemoides',
    'Micranthemum Umbrosum',
    'Micro Sword / Lilaeopis Novaezelandiae',
    'Microsorum Pteropus Java Fern "Mini"',
    'Microsorum Pteropus Java Fern "Trident"',
    'Mini Bolbitis',
    'Mini Christmas Moss',
    'Myriophyllum Aquaticum',
    'Najas Indica',
    'Nymphaea Stellata',
    'Nymphaea Tiger Lotus',
    'Nymphiodes Aquatica',
    'Peacock Moss',
    'Pinoh',
    'Piptospatha Ridleyi',
    'Piptospatha SP',
    'Pista Stratiotes',
    'Pogostemon Erectus',
    'Pogostemon Helferi "Downoi"',
    'Porserpinaca Palustris',
    'Ranunculus Inundatus',
    'Riccardia Chemdryfolia "Mini Pellia"',
    'Riccia Fluitans',
    'Rotala Ceylon',
    'Rotala Coin Leaf',
    "Rotala Vietnam H'ra",
    'Rotala Indica',
    'Rotala Indica "Bonsai"',
    'Rotala Macandra',
    'Rotala Macandra Mini',
    'Rotala Mexicana',
    'Rotala Red Cross',
    'Rotala Rotundifolia',
    'Rotala Small Leaf',
    'Rotala Sp. Araguaia',
    'Rotala Sp. Colorata',
    'Rotala Sp. Green',
    'Rotala Wallichii',
    'Sagittaria Subulata',
    'Salvinia Cucullata',
    'Salvinia Natans',
    'Schismatoglottis Roseopatha',
    'Spikey Moss',
    'Staurogyne Repens',
    'Tonina Fluviatilis',
    'Tonina SP Belem',
    'Utricularia Graminifolia',
    'Vallisneria Americana',
    'Vallisneria Gigantea',
    'Vallisneria Gigantea "Rubra"',
    'Vallisneria Nana',
    'Vallisneria Spiralis',
    'Vallisneria Torta',
    'Weeping Moss',
]
