export default {
    NON_EXISTING_USER: 'NON_EXISTING_USER',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
    BAD_REQUEST: 'BAD_REQUEST',
}
