export const tokens = {
    USERS_PROVIDER: 'USERS_PROVIDER',
    FOLLOW_PROVIDER: 'FOLLOW_PROVIDER',
    AUTH_PROVIDER: 'AUTH_PROVIDER',
    AQUASCAPE_PROVIDER: 'AQUASCAPE_PROVIDER',

    USER_REPOSITORY: 'USER_REPOSITORY',
    FOLLOW_REPOSITORY: 'FOLLOW_REPOSITORY',
    AQUASCAPE_REPOSITORY: 'AQUASCAPE_REPOSITORY'
}