export const tokens = {
    USER_PROVIDER: 'USERS_PROVIDER',
    FOLLOW_PROVIDER: 'FOLLOW_PROVIDER',
    AUTH_PROVIDER: 'AUTH_PROVIDER',
    AQUASCAPE_PROVIDER: 'AQUASCAPE_PROVIDER',
    LIGHT_PROVIDER: 'LIGHT_PROVIDER',
    BRAND_PROVIDER: 'BRAND_PROVIDER',
    LIKE_PROVIDER: 'LIKE_PROVIDER',
    VISITOR_PROVIDER: 'VISITOR_PROVIDER',
    TAG_PROVIDER: 'TAG_PROVIDER',
    AQUASCAPE_IMAGE_PROVIDER: 'AQUASCAPE_IMAGE_PROVIDER',

    USER_REPOSITORY: 'USER_REPOSITORY',
    LIKE_REPOSITORY: 'LIKE_REPOSITORY',
    SOCIAL_LOGIN_REPOSITORY: 'SOCIAL_LOGIN_REPOSITORY',
    FOLLOW_REPOSITORY: 'FOLLOW_REPOSITORY',
    AQUASCAPE_REPOSITORY: 'AQUASCAPE_REPOSITORY',
    VISITOR_REPOSITORY: 'VISITOR_REPOSITORY',
    LIGHT_REPOSITORY: 'LIGHT_REPOSITORY',
    BRAND_REPOSITORY: 'BRAND_REPOSITORY',
    TAG_REPOSITORY: 'TAG_REPOSITORY',
    AQUASCAPE_IMAGE_REPOSITORY: 'AQUASCAPE_IMAGE_REPOSITORY'
}