export {default as HeroSection} from './HeroSection'
export {default as FloraSection} from './FloraSection'
export {default as EquipmentSection} from './EquipmentSection'
export {default as UserAquascapesSection} from './UserAquascapesSection'
export {default as OtherAquascapesSection} from './OtherAquascapesSection'
export {default as PhotoSection} from './PhotoSection'