export {default as AuthModal} from './AuthModal'
export {default as LoginModal} from './LoginModal'
export {default as LoginForm} from './LoginModal/LoginForm'
export {default as RegistrationModal} from './RegistrationModal'
export {default as FeedbackModal} from './FeedbackModal'
export {default as RegistrationForm} from './RegistrationModal/RegistrationForm'